CREATE SEQUENCE "public"."agent_profile_revision_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "agent_enrollments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"parent_user_id" uuid NOT NULL,
	"status" text NOT NULL,
	"draft_profile" jsonb,
	"pairing_code_hash" text,
	"pairing_expires_at" timestamp with time zone,
	"paired_at" timestamp with time zone,
	"confirmed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agent_event_cursors" (
	"source" text NOT NULL,
	"agent_id" text NOT NULL,
	"last_sequence" bigint NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "agent_event_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_event_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_id" text NOT NULL,
	"agent_id" text NOT NULL,
	"source" text NOT NULL,
	"source_sequence" bigint NOT NULL,
	"event_type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"observed_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agent_event_log_event_id_unique" UNIQUE("event_id")
);
--> statement-breakpoint
CREATE TABLE "agent_latest_states" (
	"agent_id" text PRIMARY KEY NOT NULL,
	"presence_source" text,
	"presence_sequence" bigint,
	"presence_event_id" text,
	"presence_action" text,
	"scene_point_id" text,
	"presence_observed_at" timestamp with time zone,
	"state_source" text,
	"state_sequence" bigint,
	"state_event_id" text,
	"state" text,
	"task_summary" text,
	"state_observed_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "agent_latest_states_presence_event_id_unique" UNIQUE("presence_event_id"),
	CONSTRAINT "agent_latest_states_state_event_id_unique" UNIQUE("state_event_id")
);
--> statement-breakpoint
CREATE TABLE "agent_profiles" (
	"agent_id" text PRIMARY KEY NOT NULL,
	"schema_version" integer DEFAULT 1 NOT NULL,
	"enrollment_id" uuid,
	"owner_id" uuid,
	"legacy_owner_id" text,
	"display_name" text NOT NULL,
	"character_variant" text NOT NULL,
	"registered_by" text NOT NULL,
	"role" text,
	"personality_summary" text,
	"capabilities" jsonb,
	"color" text,
	"revision" bigint DEFAULT nextval('agent_profile_revision_seq') NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"archived_at" timestamp with time zone,
	CONSTRAINT "agent_profiles_enrollment_id_unique" UNIQUE("enrollment_id")
);
--> statement-breakpoint
CREATE TABLE "event_outbox" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_outbox_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"topic" text NOT NULL,
	"aggregate_id" text NOT NULL,
	"payload" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"attempt_count" integer DEFAULT 0 NOT NULL,
	"last_error_code" text
);
--> statement-breakpoint
CREATE TABLE "parent_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"oidc_issuer" text NOT NULL,
	"oidc_subject" text NOT NULL,
	"email" text,
	"display_name" text NOT NULL,
	"avatar_url" text,
	"timezone" text,
	"language" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "provider_agent_bindings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider" text NOT NULL,
	"native_agent_id" text NOT NULL,
	"agent_id" text,
	"runtime_instance_id" text,
	"status" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agent_enrollments" ADD CONSTRAINT "agent_enrollments_parent_user_id_parent_users_id_fk" FOREIGN KEY ("parent_user_id") REFERENCES "public"."parent_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_event_cursors" ADD CONSTRAINT "agent_event_cursors_agent_id_agent_profiles_agent_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agent_profiles"("agent_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_event_log" ADD CONSTRAINT "agent_event_log_agent_id_agent_profiles_agent_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agent_profiles"("agent_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_latest_states" ADD CONSTRAINT "agent_latest_states_agent_id_agent_profiles_agent_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agent_profiles"("agent_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_profiles" ADD CONSTRAINT "agent_profiles_enrollment_id_agent_enrollments_id_fk" FOREIGN KEY ("enrollment_id") REFERENCES "public"."agent_enrollments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_profiles" ADD CONSTRAINT "agent_profiles_owner_id_parent_users_id_fk" FOREIGN KEY ("owner_id") REFERENCES "public"."parent_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "provider_agent_bindings" ADD CONSTRAINT "provider_agent_bindings_agent_id_agent_profiles_agent_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agent_profiles"("agent_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "agent_enrollments_parent_idx" ON "agent_enrollments" USING btree ("parent_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "agent_event_cursors_source_agent_uq" ON "agent_event_cursors" USING btree ("source","agent_id");--> statement-breakpoint
CREATE UNIQUE INDEX "agent_event_log_source_sequence_uq" ON "agent_event_log" USING btree ("source","agent_id","source_sequence");--> statement-breakpoint
CREATE INDEX "agent_event_log_agent_created_idx" ON "agent_event_log" USING btree ("agent_id","id");--> statement-breakpoint
CREATE INDEX "agent_profiles_owner_idx" ON "agent_profiles" USING btree ("owner_id");--> statement-breakpoint
CREATE INDEX "agent_profiles_active_idx" ON "agent_profiles" USING btree ("archived_at");--> statement-breakpoint
CREATE INDEX "event_outbox_pending_idx" ON "event_outbox" USING btree ("published_at","id");--> statement-breakpoint
CREATE INDEX "event_outbox_topic_idx" ON "event_outbox" USING btree ("topic","id");--> statement-breakpoint
CREATE UNIQUE INDEX "parent_users_oidc_identity_uq" ON "parent_users" USING btree ("oidc_issuer","oidc_subject");--> statement-breakpoint
CREATE UNIQUE INDEX "provider_agent_bindings_native_uq" ON "provider_agent_bindings" USING btree ("provider","native_agent_id");--> statement-breakpoint
CREATE INDEX "provider_agent_bindings_agent_idx" ON "provider_agent_bindings" USING btree ("agent_id");
--> statement-breakpoint
INSERT INTO "agent_profiles" (
	"agent_id", "schema_version", "display_name", "character_variant",
	"registered_by", "role", "color", "revision", "updated_at"
) VALUES
	('agent-scout', 1, '小探', 'boy', 'system', 'Research agent', '#1677b8', 1, '2026-07-18T00:00:00.000Z'),
	('agent-bloom', 1, '小花', 'girl', 'system', 'Writing agent', '#df4c5e', 2, '2026-07-18T00:00:00.000Z'),
	('agent-spark', 1, '小光', 'genderless', 'system', 'Execution agent', '#6576d8', 3, '2026-07-18T00:00:00.000Z')
ON CONFLICT ("agent_id") DO NOTHING;
--> statement-breakpoint
SELECT setval('agent_profile_revision_seq', GREATEST(3, (SELECT COALESCE(MAX("revision"), 3) FROM "agent_profiles")), true);
